// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhd7lf9azSRmlitjGwwfw_bxmOd3igcM',
    appId: '1:431093041285:web:84b2e9504d159ff43a41ec',
    messagingSenderId: '431093041285',
    projectId: 'equipment-app-2b003',
    authDomain: 'equipment-app-2b003.firebaseapp.com',
    storageBucket: 'equipment-app-2b003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjceO0QpexTJp0l-TI-bfqRa7EKKhLFwc',
    appId: '1:431093041285:android:b0f4a9d1c935eb8d3a41ec',
    messagingSenderId: '431093041285',
    projectId: 'equipment-app-2b003',
    storageBucket: 'equipment-app-2b003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTbH4u0a2cGqPs6hjf5TLokB97sCG7WxE',
    appId: '1:431093041285:ios:78c60ad90a0ab1e33a41ec',
    messagingSenderId: '431093041285',
    projectId: 'equipment-app-2b003',
    storageBucket: 'equipment-app-2b003.appspot.com',
    iosClientId: '431093041285-rikll0p87kegnh2tqmqcupscuhb7v53a.apps.googleusercontent.com',
    iosBundleId: 'com.wermeckes.equipmentApp',
  );
}
